[package]
name = "weatherdata"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = "0.12.5"
scraper = "0.19.0"
select = "0.6.0"
tokio = { version = "1", features = ["full"] }
chrono = "0.4.38"
mysql = "25.0.1"
url = "2.4.0"
